#!/usr/bin/env python3
"""Generate the firmware Digimon type table from data/digimon/types.json.

The JSON file is the editable source of truth. The firmware only consumes the
compact generated C++ table, so runtime typing never depends on names, device
version, or style heuristics.
"""
from __future__ import annotations
import argparse, json, re, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'data/digimon/types.json'
OUT=ROOT/'digimon_types.generated.h'
CPP=ROOT/'digimon.cpp'
VALID={'NORMAL','FIRE','WATER','ELECTRIC','GRASS','ICE','FIGHTING','POISON','GROUND','FLYING','PSYCHIC','BUG','ROCK','GHOST','DRAGON','DARK','STEEL','FAIRY'}

def load_species():
    txt=CPP.read_text(encoding='utf-8')
    return [(m.group(1),int(m.group(2)),int(m.group(3))) for m in re.finditer(r'D\("([^"]+)",(\d+),(\d+),(\d+),(\d+)\)',txt)]

def render():
    doc=json.loads(SRC.read_text(encoding='utf-8'))
    entries=doc.get('entries',[])
    species=load_species()
    if len(entries)!=len(species):
        raise SystemExit(f'type entry count {len(entries)} != species count {len(species)}')
    lines=['#pragma once','// AUTO-GENERATED by tools/generate_digimon_types.py.','// Edit data/digimon/types.json instead of this file.','', 'static const DigiTypeProfile DIGI_TYPE_PROFILE[] = {']
    dual=0
    for i,(e,(name,ver,stage)) in enumerate(zip(entries,species)):
        if int(e.get('index',-1))!=i or e.get('name')!=name or int(e.get('version',-1))!=ver or int(e.get('stage',-1))!=stage:
            raise SystemExit(f'type row {i} no longer matches DIGI_SPECIES: {e} vs {(name,ver,stage)}')
        t1=e.get('type1'); t2=e.get('type2','NONE')
        if t1 not in VALID or (t2!='NONE' and t2 not in VALID):
            raise SystemExit(f'invalid type at {i}: {t1}/{t2}')
        if t1==t2:
            raise SystemExit(f'duplicate dual type at {i}: {t1}')
        if t2!='NONE': dual+=1
        c2='T_NONE' if t2=='NONE' else f'T_{t2}'
        lines.append(f'  {{ T_{t1}, {c2} }},  // {i:03d} v{ver} {name}')
    lines += ['};', 'static_assert(sizeof(DIGI_TYPE_PROFILE)/sizeof(DIGI_TYPE_PROFILE[0]) == DIGI_SPECIES_COUNT, "Digimon type table mismatch");', '', f'// dual={dual} single={len(entries)-dual}', '']
    return '\n'.join(lines)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
    text=render()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding='utf-8')!=text:
            print('digimon_types.generated.h is stale; run tools/generate_digimon_types.py',file=sys.stderr); return 1
        print('Digimon explicit type table is current')
        return 0
    OUT.write_text(text,encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}')
    return 0
if __name__=='__main__': raise SystemExit(main())
