#!/usr/bin/env python3
from pathlib import Path
import re, sys
ROOT=Path(__file__).resolve().parents[1]
ino=(ROOT/'TamaPoke.ino').read_text(encoding='utf-8')
mir=(ROOT/'firmware_source/TamaPoke.ino').read_text(encoding='utf-8')
ph=(ROOT/'pet.h').read_text(encoding='utf-8')
pc=(ROOT/'pet.cpp').read_text(encoding='utf-8')
ah=(ROOT/'audio.h').read_text(encoding='utf-8')
ac=(ROOT/'audio.cpp').read_text(encoding='utf-8')
saveh=(ROOT/'save.h').read_text(encoding='utf-8')
fh=(ROOT/'feedback.h').read_text(encoding='utf-8')
fc=(ROOT/'feedback.cpp').read_text(encoding='utf-8')
wf=(ROOT/'.github/workflows/main.yml').read_text(encoding='utf-8')
inst=(ROOT/'TamaPoke-KO-OneClick-Installer.html').read_text(encoding='utf-8')
checks=[]
def ck(name, ok): checks.append((name,bool(ok)))

m_fw=re.search(r'#define\s+FW_VERSION\s+\"(\d+)\.(\d+)\.(\d+)\"', ino)
ck('FW 3.107.0+', bool(m_fw) and tuple(map(int,m_fw.groups())) >= (3,107,0))
ck('SAVE_VERSION remains 2', re.search(r'#define\s+SAVE_VERSION\s+2\b', saveh) is not None)
ck('wild rarity enum has 3 tiers', all(x in ino for x in ['WILD_COMMON=0','WILD_RARE=1','WILD_VERY_RARE=2']))
ck('wild fixed 72/23/5 roll', 'roll < 72 ? WILD_COMMON : roll < 95 ? WILD_RARE : WILD_VERY_RARE' in ino)
ck('wild tier sampler unregistered only', 'pickWildUnregisteredTier' in ino and '!pet.isRegistered(d)' in ino and '!pet.isDigiRegistered(d)' in ino)
ck('wild tier fallback exists', 'order[3][3]' in ino and 'for(uint8_t i=0;i<3;i++)' in ino)
ck('Pokemon rarity uses dex rarity', 'DEX_TBL[dex].rarity' in ino and 'R_LEGENDARIO' in ino and 'R_RARO' in ino)
ck('Digimon rarity uses evolution stage', 'DIGI_SPECIES[digimonIndex(dex)].stage' in ino and 'DIGI_ULTIMATE' in ino and 'DIGI_ADULT' in ino)
ck('rarity labels visible', all(x in ino for x in ['"일반"','"희귀"','"매우 희귀"','일반 72% · 희귀 23% · 매우 희귀 5%']))
ck('rare discovery feedback', 'if(wildCandidateRarity){ sfxPlay(SFX_DISCOVER);' in ino)

ck('player pages add collection page', '#define PLAYER_PAGES (GYM_REGIONS + 3)' in ino and 'renderCollectionProgress()' in ino)
ck('Pokemon dex progress', 'pet.registeredCount()' in ino and 'regionDexCount(REGION_ALL)' in ino)
ck('Digimon dex progress', 'pet.digiRegisteredCount()' in ino and 'DIGI_SPECIES_COUNT' in ino)
ck('Shiny progress', 'pet.shinyRegisteredCount()' in ino and 'pet.digiShinyRegisteredCount()' in ino)
ck('wild Jogress material progress', 'pet.digiWildMaterialCount()' in ino and '야생 Jogress 소재' in ino)
ck('count helpers exist', 'uint16_t shinyRegisteredCount() const;' in ph and 'digiShinyRegisteredCount() const' in ph and 'digiWildMaterialCount() const' in ph and 'Pet::shinyRegisteredCount() const' in pc)
ck('collection next goal shown', 'nextCollectionGoal' in ino and '다음 목표' in ino)

ck('transient evolution kind exists', 'uint8_t evolveKind = 0;' in ph and 'evolvingJogress() const' in ph)
ck('normal evolution marks kind 1', pc.count('evolveKind=1') >= 2)
ck('Jogress marks kind 2', 'evolveKind=2;' in pc)
ck('Jogress distinct sound', 'sfxPlay(SFX_JOGRESS)' in pc)
ck('evolution transition overlay exists', 'drawEvolutionTransitionOverlay' in ino)
ck('normal EVOLUTION presentation', '"EVOLUTION"' in ino)
ck('Jogress fusion presentation', '"JOGRESS"' in ino and 'pet.evolvingJogress()' in ino)
ck('transition reaches PMD/DGI/fallbacks', ino.count('drawEvolutionTransitionOverlay(') >= 5)

ck('new sound enums', all(x in ah for x in ['SFX_CRIT','SFX_DISCOVER','SFX_JOGRESS']))
ck('new sound note tables', all(x in ac for x in ['N_CRIT','N_DISCOVER','N_JOGRESS']))
ck('critical cue wired', 'if (lg.crit) { sfxPlay(SFX_CRIT)' in ino)
ck('new dex discovery cue wired', 'sfxPlay(SFX_DISCOVER)' in ino and 'btlArmDexNew' in ino)
ck('feedback module present', all(x in fh for x in ['feedbackBegin','feedbackUpdate','feedbackPulse','feedbackHapticAvailable']))
ck('stock haptic defaults disabled', '#define TAMAPOKE_HAPTIC_PIN (-1)' in fc)
ck('optional haptic is nonblocking', 'gHapticUntil' in fc and 'feedbackUpdate()' in fc and 'delay(' not in fc)
ck('feedback lifecycle wired', 'feedbackBegin();' in ino and 'feedbackUpdate();' in ino)
ck('root and firmware mirror exact', ino == mir)
ck('workflow runs 3.107 verifier', 'verify_collection_rarity_fx_v31070.py' in wf)
m_inst=re.search(r'const\s+FW_VERSION\s*=\s*\"(\d+)\.(\d+)\.(\d+)(?:-[^\"]*)?\"', inst)
ck('installer marker 3.107+', bool(m_inst) and tuple(map(int,m_inst.groups())) >= (3,107,0))

bad=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL')+': '+n)
print(f'\n{len(checks)-len(bad)}/{len(checks)} checks passed')
if bad:
    sys.exit(1)
